<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-17 at 02:16:30.
 */
class BaseIntConvertTask2Test extends PHPUnit_Framework_TestCase {

    /**
     * @var BaseIntConvertTask2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        require_once dirname(__FILE__) . '/../BaseIntConvertTask2.php';
        $this->object = new BaseIntConvertTask2;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (array(4,5,6,7,8,9,10,11)) == "4 Buzz Fizz Bazz 8 Fizz Buzz Bazz ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString() {
        $this->assertEquals(
                "4 Buzz Fizz Bazz 8 Fizz Buzz Bazz "
                , $this->object->convertingIntString(array(4, 5, 6, 7, 8, 9, 10, 11))
        );
    }

    /**
     * Generated from @assert (array(1,2,4,5,7,9,20,21,23,26)) == "1 2 4 Buzz 7 Fizz Buzz Fizz Bazz 26 ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString2() {
        $this->assertEquals(
                "1 2 4 Buzz 7 Fizz Buzz Fizz Bazz 26 "
                , $this->object->convertingIntString(array(1, 2, 4, 5, 7, 9, 20, 21, 23, 26))
        );
    }

    /**
     * Generated from @assert (array(11,15,18,20,22,25)) == "11 FizzBuzz Fizz Buzz Bazz Buzz ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString3() {
        $this->assertEquals(
                "11 FizzBuzz Fizz Buzz Bazz Buzz "
                , $this->object->convertingIntString(array(11, 15, 18, 20, 22, 25))
        );
    }

    /**
     * Generated from @assert (array(33,35,37,41,43,50,51,62)) == "Fizz Buzz Bazz 41 43 Buzz Fizz Bazz ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString4() {
        $this->assertEquals(
                "Fizz Buzz Bazz 41 43 Buzz Fizz Bazz "
                , $this->object->convertingIntString(array(33, 35, 37, 41, 43, 50, 51, 62))
        );
    }

    /**
     * Generated from @assert (array(3,5,7,9,11,13,15,17,19,21,22)) == "Fizz Buzz Bazz Fizz 11 13 FizzBuzz 17 19 Fizz 22 ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString5() {
        $this->assertEquals(
                "Fizz Buzz Bazz Fizz 11 13 FizzBuzz 17 19 Fizz 22 "
                , $this->object->convertingIntString(array(3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 22))
        );
    }
    
    /**
     * Generated from @assert (array(3,6,7,10,12,14)) == "Fizz Fizz Bazz Buzz Fizz Bazz ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString6() {
        $this->assertEquals(
                "Fizz Fizz Bazz Buzz Fizz Bazz "
                , $this->object->convertingIntString(array(3,6,7,10,12,14))
        );
    }
    
    /**
     * Generated from @assert (array(15,30,44,45,51,52)) == "FizzBuzz FizzBuzz Bazz FizzBuzz Fizz Bazz ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString7() {
        $this->assertEquals(
                "FizzBuzz FizzBuzz Bazz FizzBuzz Fizz Bazz "
                , $this->object->convertingIntString(array(15,30,44,45,51,52))
        );
    }
    
    /**
     * Generated from @assert (array(5,10,11,13)) == "Buzz Buzz Bazz 13 ".
     *
     * @covers BaseIntConvertTask2::convertingIntString
     */
    public function testConvertingIntString8() {
        $this->assertEquals(
                "Buzz Buzz Bazz 13 "
                , $this->object->convertingIntString(array(5,10,11,13))
        );
    }

    /**
     * @covers BaseIntConvertTask2::changeIntBazz
     * @todo   Implement testChangeIntBazz().
     */
    public function testChangeIntBazz() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseIntConvertTask2::checkint
     * @todo   Implement testCheckint().
     */
    public function testCheckint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
