<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-17 at 00:49:05.
 */
class BaseIntConvertTest extends PHPUnit_Framework_TestCase {

    /**
     * @var BaseIntConvert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        require_once dirname(__FILE__) . '/../BaseIntConvert.php';
        $this->object = new BaseIntConvert;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (array(1,2,3,4,5,6,7,8,9,10)) == "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz ".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString() {
        $this->assertEquals(
                "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz ", $this->object->convertingIntString(array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
        );
    }

    /**
     * Generated from @assert (array(4,5,6,8,9,12,15)) == "4 Buzz Fizz 8 Fizz Fizz FizzBuzz ".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString2() {
        $this->assertEquals(
                "4 Buzz Fizz 8 Fizz Fizz FizzBuzz ", $this->object->convertingIntString(array(4, 5, 6, 8, 9, 12, 15))
        );
    }

    /**
     * Generated from @assert (array(5,7,9,10,15,16,18,20,24,30)) == "Buzz 7 Fizz Buzz FizzBuzz 16 Fizz Buzz Fizz FizzBuzz ".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString3() {
        $this->assertEquals(
                "Buzz 7 Fizz Buzz FizzBuzz 16 Fizz Buzz Fizz FizzBuzz ", $this->object->convertingIntString(array(5, 7, 9, 10, 15, 16, 18, 20, 24, 30))
        );
    }

    /**
     * Generated from @assert (array(10,24,30,40,45)) == "Buzz Fizz FizzBuzz Buzz FizzBuzz ".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString4() {
        $this->assertEquals(
                "Buzz Fizz FizzBuzz Buzz FizzBuzz ", $this->object->convertingIntString(array(10, 24, 30, 40, 45))
        );
    }

    /**
     * Generated from @assert (array(6,10,19,20,25,105)) == "Fizz Buzz 19 Buzz Buzz FizzBuzz ".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString5() {
        $this->assertEquals(
                "Fizz Buzz 19 Buzz Buzz FizzBuzz ", $this->object->convertingIntString(array(6, 10, 19, 20, 25, 105))
        );
    }

    /**
     * Generated from @assert (array(6,-10,19,20,25,105)) == "Integer list not positive integers".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString6() {
        $this->assertEquals(
                "Invalid input! Please enter positive integer values only!", $this->object->convertingIntString(array(6, -10, 19, 20, 25, 105))
        );
    }

    /**
     * Generated from @assert (array(6,"a",19,20,25,105)) == "Integer list not positive integers".
     *
     * @covers BaseIntConvert::convertingIntString
     */
    public function testConvertingIntString7() {
        $this->assertEquals(
                "Invalid input! Please enter positive integer values only!", $this->object->convertingIntString(array(6, "a", 19, 20, 25, 105))
        );
    }

    /**
     * @covers BaseIntConvert::checkint
     * @todo   Implement testCheckint().
     */
    public function testCheckint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}